"""empty message

Revision ID: 4441530d6b8f
Revises: 6da7a8ec5c4f
Create Date: 2019-05-30 08:35:49.997577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4441530d6b8f'
down_revision = '6da7a8ec5c4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('type', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
