"""empty message

Revision ID: 6da7a8ec5c4f
Revises: fba820791230
Create Date: 2019-05-29 07:51:16.708790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6da7a8ec5c4f'
down_revision = 'fba820791230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('bboxed_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'bboxed_filename')
    # ### end Alembic commands ###
