"""empty message

Revision ID: ba6fe57eb2a2
Revises: a5b1d0cbd74e
Create Date: 2019-05-30 12:29:08.089035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba6fe57eb2a2'
down_revision = 'a5b1d0cbd74e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('pose_image_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'pose_image_filename')
    # ### end Alembic commands ###
