"""empty message

Revision ID: fba820791230
Revises: 
Create Date: 2019-05-28 20:24:22.872992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fba820791230'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instagram_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('analyzed', sa.Boolean(), nullable=True),
    sa.Column('instagram_id', sa.String(length=100), nullable=True),
    sa.Column('attractiveness', sa.Float(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('profile_picture_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('shortcode', sa.String(), nullable=True),
    sa.Column('public_url', sa.String(), nullable=True),
    sa.Column('instagram_user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('racy_score', sa.Float(), nullable=True),
    sa.Column('adult_score', sa.Float(), nullable=True),
    sa.Column('golden_ratio', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('analyze_response', sa.String(), nullable=True),
    sa.Column('face_response', sa.String(), nullable=True),
    sa.Column('emotions_json', sa.String(), nullable=True),
    sa.Column('apparel_response', sa.String(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instagram_user_id'], ['instagram_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('payment', sa.Boolean(), nullable=True),
    sa.Column('analyzed', sa.Boolean(), nullable=True),
    sa.Column('instagram_id', sa.String(length=100), nullable=True),
    sa.Column('instagram_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instagram_user_id'], ['instagram_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('value', sa.Enum('login', 'logout', 'invalid_credentials', name='logenum'), nullable=True),
    sa.Column('ip_address', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_log')
    op.drop_table('user')
    op.drop_table('photo')
    op.drop_table('instagram_user')
    # ### end Alembic commands ###
